added dl
Script to automagically download contents based on the url

USAGE: dl [OPTIONS] SOURCE

The behaviour of the script depends on the given source:
 - YouTube links (sources starting with 'https://www.youtube.com/' or
        'https://youtu.be/') will be downloaded using yt-dlp, defaulting to .mp4
 - Anything else will be downloaded with wget

OPTIONS:
    -h, --help                 print help text
    -o, --output OUTPUT        set the name of the output file. If downloading
                               with yt-dlp, it is not necessary to add the file
                               extension. If added anyway, it will be stripped
                               and then added back by yt-dlp itself
    --mp3                      if downloading with yt-dlp, downlaod in mp3

ERROR: Source not given script utility